name: Run Discord Bot

on:
  schedule:
    - cron: "0 4 * * *"  # TEST
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        timeout-minutes: 5

      - name: Set up Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
        timeout-minutes: 5

      - name: Run bot
        run: python bot.py
        timeout-minutes: 5
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
